### ISSUE TITLE
Create inference pipeline

### ISSUE THREAD

**Issue by typicalTYLER** [typicalTYLER/DeepSolar#1]
Modify the model to run inference on arbitrary tile batches (currently just runs on test set).

**Comment by sallamander** [comment]
@typicalTYLER if you wouldn't mind, can I get some permissions to be able to assign myself to an issue as well as push, commit, etc. to non-master branches, please?

**Comment by sallamander** [comment]
If you'd rather I fork this and issue PRs that way, I'm OK with that too (although my current plan was to just issue PRs off a separate branch).

**Comment by sallamander** [comment]
Perfect, thanks!!

**Comment by typicalTYLER** [comment]
Sure! I can add you as a collaborator. I'm not sure if there's a way to allow anybody to assign themselves an issue without directly giving them push access.

**Comment by sallamander** [comment]
Perfect, thanks!!

**Comment by typicalTYLER** [comment]
Resolved by 816addb
